name: feedback
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app.
version: 3.0.0
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues
publish_to: https://pub.trugman.com/

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter